import { openai, supabase } from "./config.js"

export async function vectorSearch(input) {
    try {
        const response = await openai.embeddings.create({
            model: "text-embedding-3-small",
            input,
            encoding_format: "float",
        })

        // The vector generated by OpenAI
        const embedding = response.data[0].embedding

        // Query Supabase for nearest vector match
        const { data } = await supabase.rpc('match_documents', {
            query_embedding: embedding,
            match_threshold: 0.7,
            match_count: 1,
        })
        return data
    } catch (error) {
        console.error('Error in vector search:', error);
        throw error;
    }
}